meta_product_name: "UFCode"
meta_title: "UFCode - Code, Catch, Conquer. Challenge your programming skills!"
meta_description: "Challenge your programming skills and oppose them to your friend while having fun!"
meta_image: "kitt-background.png"
twitter_account: "@product_twitter_account"
